matrix:
  include:
    - os: osx
      osx_image: xcode9.3
    - os: linux
  allow_failures:
    - os: osx
    - python: 3.7-dev

language: python
cache: pip
python:
  - "3.6"
  - "3.7-dev"

before_install:
  - pip install pipenv
#  - pip install pytest-cov
install:
  - pipenv install --dev

script: pipenv run pytest

after_success:
  - codecov
