os:
  - osx
  - linux

matrix:
  allow_failures:
    - os: osx
    - python: 3.7

language: python
cache: pip
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

before_install:
  - pip install pipenv
#  - pip install pytest-cov
install:
  - pipenv install --dev

script: pipenv run pytest

after_success:
  - codecov
