language: python
cache: pip
python:
  - "3.6"
  - "3.7-dev"
  #- "pypy3"

matrix:
  allow_failures:
    - python: "pypy3"

before_install:
  - pip install pipenv
  - pip install poetry
  - pip install codecov
#  - pipenv install --dev
  -  pip install https://github.com/damndam/webdavfs/tarball/master
#  - pip install pytest-cov
#  - pip install pytest
#  - pip install -r requirements.txt
install:
  - poetry install

script: pipenv run pytest

after_success:
  - codecov
