language: python
cache: pip
python:
  - "3.6"
  - "3.7-dev"

before_install:
  - pip install pipenv
  - pip install codecov
#  - pip install pytest-cov
#  - pip install pytest
#  - pip install -r requirements.txt
install:
  - pipenv install --dev

script: pipenv run pytest

after_success:
  - codecov
