#Email address for your lastpass account
Email: johnsmith@example.com
# Trust: whether to trust this computer after backing up
Trust: true
# Options:
# null: do not encrypt
# generate: generate a new key (it will be written to this file. Don't lose it!)
# a key represented as a 32 url safe base64-encoded bytes, either generated or your own.
Encryption Key: generate
# Compress the data or not
Compression: true

# Where to put the final backup. Specify a uri as documented at
# http://pyfilesystem2.readthedocs.io/en/latest/builtin.html for osfs,
# mountfs, ftpfs. You can use non-native filesystems (e.g. sshfs) but you will
# need to install the corresponding extensions to pyfilesystem2. Obviously this
# must be accessible to the backup program when it runs.
# Backing Store:
#   URI: /home/backupuser/backups
# You may also specify S3 for Amazon Simple Storage Service or s3 compatible service.
# It is recommended that you use external authentication for S3 (env vars or
# IAM roles), but you may specify Key ID and Secret Key, preferably through
# env vars.
# Be sure to specify Endpoint URL and ensure authentication for S3 compatible services
# Specify Date: True for adding date information to the backup file/folders.
# Example S3 compatible service (digital ocean spaces):
#Backing Store:
#  Type: S3
#  Bucket: mybackupbucket
#  Endpoint URL: https://nyc3.digitaloceanspaces.com
#  Key ID: $DOKEY
#  Secret Key: $DOSECRET
# Example Webdav:
# <diatribe>IF YOU DO THIS: please please please don't use your main password, set up multi-factor authentication
# and generate a single app password. This is a plain text file protected only by filesystem permissions
# (which should probably be 600, by the way). Even better, make a dedicated user account for this purpose,
# so that none of your other data is put at risk. </diatribe>
#Backing Store:
#  Type: webdav
#  URL: https://mynextcloudserver.com/remote.php/webdav
#  Username: john
#  Password: my-single-app-password
#  Prefix: my/lastpass/backups
#  Date: True
Backing Store:
  Type: S3
  Bucket: mybackupbucket
  Prefix: backupfolder/
  Date: True
